-- Research-only district observations.
-- These tables intentionally contain no boundary geometry and have no public
-- RLS policy. The application exposes only a controlled aggregate projection
-- while the product remains behind the validated publication gate.

CREATE TABLE IF NOT EXISTS observatory_research_areas (
  area_code text PRIMARY KEY
    CHECK (area_code ~ '^BKK-D[0-9]{2}$'),
  source_district_code text NOT NULL
    CHECK (source_district_code ~ '^[0-9]{4}$'),
  name_th text NOT NULL,
  name_en text NOT NULL,
  source_dataset_version_id uuid NOT NULL
    REFERENCES observatory_dataset_versions(dataset_version_id)
    ON DELETE RESTRICT,
  boundary_result_checksum_sha256 text NOT NULL
    CHECK (boundary_result_checksum_sha256 ~ '^[a-f0-9]{64}$'),
  source_survey_year_buddhist integer NOT NULL
    CHECK (source_survey_year_buddhist BETWEEN 2400 AND 2700),
  area_square_meters double precision NOT NULL
    CHECK (area_square_meters > 0),
  acceptance_status text NOT NULL DEFAULT 'research'
    CHECK (acceptance_status = 'research'),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (source_dataset_version_id, source_district_code)
);

CREATE TABLE IF NOT EXISTS observatory_research_observations (
  research_observation_id bigint
    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  area_code text NOT NULL
    REFERENCES observatory_research_areas(area_code)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  product_id text NOT NULL,
  analysis_year integer NOT NULL
    CHECK (analysis_year BETWEEN 2015 AND 2100),
  season_id text NOT NULL
    CHECK (season_id IN ('hot', 'wet', 'cool')),
  period_start timestamptz NOT NULL,
  period_end timestamptz NOT NULL,
  statistic text NOT NULL
    CHECK (
      statistic IN (
        'median',
        'p10',
        'p90',
        'interquartile-range'
      )
    ),
  value double precision NOT NULL
    CHECK (
      value NOT IN (
        'NaN'::double precision,
        'Infinity'::double precision,
        '-Infinity'::double precision
      )
    ),
  unit text NOT NULL,
  valid_coverage double precision NOT NULL
    CHECK (valid_coverage BETWEEN 0 AND 1),
  scene_count integer NOT NULL
    CHECK (scene_count >= 0),
  valid_observation_count bigint NOT NULL
    CHECK (valid_observation_count >= 0),
  processing_run_id uuid NOT NULL,
  source_manifest_checksum_sha256 text NOT NULL
    CHECK (source_manifest_checksum_sha256 ~ '^[a-f0-9]{64}$'),
  boundary_result_checksum_sha256 text NOT NULL
    CHECK (boundary_result_checksum_sha256 ~ '^[a-f0-9]{64}$'),
  quality_status text NOT NULL
    CHECK (quality_status IN ('accepted', 'rejected')),
  created_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (processing_run_id, product_id)
    REFERENCES observatory_processing_runs(processing_run_id, product_id)
    ON DELETE RESTRICT,
  UNIQUE (
    area_code,
    product_id,
    analysis_year,
    season_id,
    statistic,
    processing_run_id
  ),
  CHECK (period_end >= period_start),
  CHECK (
    statistic = 'interquartile-range'
    OR value BETWEEN -1 AND 1
  ),
  CHECK (
    statistic <> 'interquartile-range'
    OR value BETWEEN 0 AND 2
  )
);

CREATE INDEX IF NOT EXISTS idx_observatory_research_observations_lookup
  ON observatory_research_observations (
    processing_run_id,
    product_id,
    analysis_year,
    season_id,
    statistic,
    area_code
  );

ALTER TABLE observatory_research_areas ENABLE ROW LEVEL SECURITY;
ALTER TABLE observatory_research_observations ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON observatory_research_areas
  FROM anon, authenticated;
REVOKE ALL ON observatory_research_observations
  FROM anon, authenticated;

GRANT SELECT, INSERT, UPDATE ON observatory_research_areas
  TO service_role;
GRANT SELECT, INSERT, UPDATE ON observatory_research_observations
  TO service_role;
GRANT USAGE, SELECT ON SEQUENCE
  observatory_research_observations_research_observation_id_seq
  TO service_role;

COMMENT ON TABLE observatory_research_areas IS
  'Research district index and area metadata only. No source geometry is stored.';
COMMENT ON TABLE observatory_research_observations IS
  'Research-only derived district statistics. Public validated observations remain separate.';
